---
# editorconfig-checker-disable
# yamllint disable rule:line-length

default_language_version:
    python: python3

repos:

  # precommit configuration meta-checks
    - repo: meta
      hooks:
          - id: check-hooks-apply
            always_run: true
          - id: check-useless-excludes
            always_run: true

    - repo: https://github.com/mattlqx/pre-commit-sign
      rev: v1.1.3
      hooks:
          - id: sign-commit

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-json
          - id: pretty-format-json
            args: [--autofix]
          - id: check-yaml
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace

    # text and typos
    - repo: https://github.com/sirosen/texthooks
      rev: 0.3.1
      hooks:
          - id: fix-ligatures
          - id: fix-smartquotes
          - id: forbid-bidi-controls
    - repo: https://github.com/crate-ci/typos
      rev: v1.10.2 # last known stable version is typos-dict-v0.8.2
      hooks:
          - id: typos
            args: [--write-changes]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
            args: [--width, '400', --preserve-quotes]
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.27.1
      hooks:
          - id: yamllint
    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.17.1 # last known stable version is 0.14.3
      hooks:
          - id: check-github-workflows

    # Dockerfile
    - repo: https://github.com/hadolint/hadolint
      rev: v2.10.0
      hooks:
          - id: hadolint

    # check editorconfig rules
    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: 2.4.0
      hooks:
          - id: editorconfig-checker

ci:
    skip: [hadolint]
    autofix_commit_msg: 'style: pre-commit autofixes [skip ci]'
    autoupdate_commit_msg: 'chore: pre-commit autoupdate [skip ci]'
