---
name: Create release

# yamllint disable rule:line-length

on:
    workflow_dispatch:
    push:
        branches:
            - main
    schedule:
        - cron: 0 0 * * 1

defaults:
    run:
        shell: bash

jobs:

    Deploy:

        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 120

        steps:

            - name: Set up QEMU
              id: setup_qemu
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  platforms: linux/arm64
                  push: true
                  tags: benvining/citrus_dev_machine:latest
